CFLAGS := -Wall -Wextra -O2 -g
CPP := c++

all: 1 2 3 4

1: 1.cpp
	$(CPP) $(CFLAGS) 1.cpp -o 1
	
2: 2.cpp
	$(CPP) $(CFLAGS) 2.cpp -o 2

3: 3.cpp
	$(CPP) $(CFLAGS) 3.cpp -o 3

4: 4.cpp
	$(CPP) $(CFLAGS) 4.cpp -o 4

clean:
	rm -f 1 2 3 4
